### ISSUE TITLE
feat: 노드 CRUD 프로토타입 제작

### ISSUE THREAD

**Issue by dionrun** [Groot-GT/groot-client#8]
### **기능**

노드 CRUD를 위한 프론트엔드 프로토타입을 구현한다.

### **완료 조건**

- [x] 노드 추가 동작 구현
- [x] 노드 삭제 동작 구현
- [x] 노드 위치 변경 동작 구현

**Comment by pinkishincoloragain** [comment]
이 브랜치에서 작업할 계획이 있으신 줄 몰랐읍니다 . .
Reopen 감사합니다.
